"""
ui/add_audio_links.py
Screen for adding audio file links to database.
"""

import pandas as pd
import streamlit as st

from tasks import (
    get_windows_batch_file,
    get_mac_shell_script,
    parse_file_list,
    analyze_folder_structure,
    analyze_filenames,
    validate_delimiter_consistency,
    add_audio_links,
    export_database,
)
from ui.navigation import Screen, navigate_to, go_back_to_menu


def screen_add_audio_links():
    """Screen for adding audio file links to database."""

    # Add vertical divider CSS
    st.markdown(
        """
        <style>
        div[data-testid="stHorizontalBlock"] > div[data-testid="stColumn"]:first-child {
            border-right: 1px solid #ccc;
            padding-right: 1.5rem !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.title("Add Audio File Links")
    st.markdown("---")

    # Two-column layout
    config_col, output_col = st.columns([1, 2])

    df = st.session_state.database
    columns = list(df.columns)

    with config_col:
        # === SECTION 1: Platform & Analysis Mode ===
        st.subheader("Configuration")

        st.markdown("**Required Settings**")

        platform = st.selectbox(
            "Operating system",
            options=["Windows", "Mac"],
            index=0,
            help="Determines file generator type and link format",
        )
        platform_key = platform.lower()

        analysis_mode = st.selectbox(
            "Analysis type",
            options=["Phonological Analysis", "Acoustic Phonetic Analysis"],
            index=0,
            help="Phonological: one audio per index. Acoustic: one row per audio file.",
        )
        analysis_key = "phonological" if "Phonological" in analysis_mode else "acoustic"

        # === SECTION 2: File List Generator ===
        st.markdown("---")
        st.subheader("Step 1: Get File List")

        if platform_key == "windows":
            st.markdown(
                """
                **Instructions:**
                1. Click **Download** below to get the file list generator
                2. Double-click the downloaded `.bat` file
                3. Drag your audio folder into the window and press Enter
                4. Upload the generated `filelist.txt` in Step 2
                """
            )
            st.download_button(
                label="Download File List Generator (.bat)",
                data=get_windows_batch_file(),
                file_name="File List Generator.bat",
                mime="application/octet-stream",
                use_container_width=True,
            )
        else:
            st.markdown(
                """
                **Instructions:**
                1. Click **Download** below to get the file list generator
                2. Open Terminal and navigate to your Downloads folder:
                   `cd ~/Downloads`
                3. Make the script executable:
                   `chmod +x "File List Generator.sh"`
                4. Run the script:
                   `bash "File List Generator.sh"`
                5. Drag your audio folder into Terminal and press Enter
                6. Upload the generated `filelist.txt` in Step 2
                """
            )
            st.download_button(
                label="Download File List Generator (.sh)",
                data=get_mac_shell_script(),
                file_name="File List Generator.sh",
                mime="application/x-sh",
                use_container_width=True,
            )

        # === SECTION 3: Upload File List ===
        st.markdown("---")
        st.subheader("Step 2: Upload File List")

        uploaded_file = st.file_uploader(
            "Upload filelist.txt",
            type=["txt"],
            help="The file generated by the file list generator tool",
        )

        # Process uploaded file
        file_paths = None
        folder_analysis = None
        filename_analysis = None

        if uploaded_file is not None:
            content = uploaded_file.read().decode('utf-8')
            file_paths, parse_error = parse_file_list(content, platform_key)

            if parse_error:
                st.error(parse_error)
            else:
                st.success(f"Found {len(file_paths)} .wav files")

                # Analyze structure
                folder_analysis = analyze_folder_structure(file_paths, platform_key)
                filename_analysis = analyze_filenames(file_paths, platform_key)

                # Store in session state for use in output column
                st.session_state._audio_file_paths = file_paths
                st.session_state._folder_analysis = folder_analysis
                st.session_state._filename_analysis = filename_analysis

        # === SECTION 4: Column Mapping (only if file uploaded) ===
        if file_paths and folder_analysis and filename_analysis:
            if folder_analysis.error:
                st.error(folder_analysis.error)
            else:
                st.markdown("---")
                st.subheader("Step 3: Configure Mapping")

                # Index column
                index_default = columns.index("index") if "index" in columns else 0
                index_col = st.selectbox(
                    "Index column (required)",
                    options=columns,
                    index=index_default,
                    help="Database column containing index values to match with filenames",
                )

                # Subfolder category (if subfolders detected)
                subfolder_category = None
                if folder_analysis.has_subfolders:
                    st.markdown(f"**Subfolders detected:** {', '.join(folder_analysis.subfolder_names[:5])}"
                                + (f" ... and {len(folder_analysis.subfolder_names) - 5} more" if len(folder_analysis.subfolder_names) > 5 else ""))
                    subfolder_category = st.selectbox(
                        "What do subfolders represent?",
                        options=["-none-", "speaker", "token", "other"],
                        index=0,
                        help="If subfolders represent a category (e.g., speaker names), select it here",
                    )

                # Filename structure
                section_categories = None
                delimiter = filename_analysis.delimiter

                if filename_analysis.all_integers:
                    st.info(f"Filenames are index numbers (e.g., `{filename_analysis.example_filename}`). No additional mapping needed.")
                    section_categories = ["index"]
                elif filename_analysis.delimiter:
                    # Validate delimiter consistency
                    delim_error = validate_delimiter_consistency(file_paths, delimiter, platform_key)
                    if delim_error:
                        st.error(delim_error)
                    else:
                        st.markdown(f"**Filename structure detected:** `{filename_analysis.example_filename}`")
                        st.markdown(f"Delimiter: `{delimiter}` → {filename_analysis.num_sections} sections")

                        section_categories = []
                        for i, section in enumerate(filename_analysis.example_sections):
                            # Auto-detect index section (if it's all digits)
                            default_idx = 0  # -none-
                            if section.isdigit():
                                default_idx = 1  # index

                            cat = st.selectbox(
                                f"Section {i + 1}: `{section}`",
                                options=["-none-", "index", "speaker", "token", "other"],
                                index=default_idx,
                                key=f"section_cat_{i}",
                            )
                            section_categories.append(cat if cat != "-none-" else None)

                        # Validate that index is selected
                        if "index" not in section_categories:
                            st.warning("You must identify which section contains the index.")
                else:
                    st.info(f"Filenames will be treated as index values (e.g., `{filename_analysis.example_filename}`).")
                    section_categories = ["index"]

                st.markdown("---")

                # Generate button
                can_generate = (
                    file_paths and
                    not folder_analysis.error and
                    section_categories and
                    ("index" in section_categories if section_categories else False)
                )

                generate_clicked = st.button(
                    "Add Audio Links",
                    type="primary",
                    use_container_width=True,
                    disabled=not can_generate,
                )

                # Store generation parameters in session state for processing in output column
                if generate_clicked:
                    st.session_state._audio_generate_params = {
                        'file_paths': file_paths,
                        'platform': platform_key,
                        'analysis_mode': analysis_key,
                        'index_col': index_col,
                        'delimiter': delimiter,
                        'section_categories': section_categories,
                        'subfolder_category': subfolder_category if subfolder_category != "-none-" else None,
                    }
                    st.rerun()

        st.markdown("---")
        if st.button("Back to Main Menu", use_container_width=True):
            # Clean up session state
            for key in ["_audio_file_paths", "_folder_analysis", "_filename_analysis", "_audio_link_result", "_audio_link_platform", "_audio_generate_params"]:
                if key in st.session_state:
                    del st.session_state[key]
            go_back_to_menu()

    # === OUTPUT COLUMN ===
    with output_col:
        st.subheader("Output")

        # Process if generation was triggered (params stored in session state)
        if "_audio_generate_params" in st.session_state:
            params = st.session_state._audio_generate_params
            del st.session_state._audio_generate_params  # Clear params

            with st.spinner("Adding audio links..."):
                result = add_audio_links(
                    df=df,
                    file_paths=params['file_paths'],
                    platform=params['platform'],
                    analysis_mode=params['analysis_mode'],
                    index_col=params['index_col'],
                    delimiter=params['delimiter'],
                    section_categories=params['section_categories'],
                    subfolder_category=params['subfolder_category'],
                )

            if result.success:
                st.session_state._audio_link_result = result
                st.session_state._audio_link_platform = params['platform']
                st.session_state._scroll_to_top = True
                st.session_state.database = result.df
                st.session_state.database_validated = True
                st.rerun()
            else:
                st.error(f"**Error:** {result.error}")

                st.markdown("---")

                if st.button("Clear Database & Start Over", type="primary", use_container_width=True):
                    for key in ["_audio_file_paths", "_folder_analysis", "_filename_analysis", "_audio_link_result", "_audio_link_platform", "_audio_generate_params"]:
                        if key in st.session_state:
                            del st.session_state[key]
                    st.session_state.database = None
                    st.session_state.database_validated = False
                    st.session_state.database_filename = None
                    st.session_state.database_sheet_name = None
                    st.session_state.selected_task = None
                    navigate_to(Screen.UPLOAD_DATABASE)

        # Show result if available
        if "_audio_link_result" in st.session_state:
            result = st.session_state._audio_link_result

            st.success("Audio links added successfully!")

            st.markdown(f"""
            **Summary:**
            - Files matched: {result.files_matched}
            - Indices without audio: {result.files_unmatched}
            - Rows before: {result.rows_before}
            - Rows after: {result.rows_after}
            """)

            st.markdown("---")

            # Buttons row
            btn_col1, btn_col2 = st.columns(2)

            with btn_col1:
                # Download updated database with formatting
                platform = st.session_state.get('_audio_link_platform', 'windows')
                st.download_button(
                    label="Download Updated Database",
                    data=export_database(result.df, platform=platform),
                    file_name="database_with_audio.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    type="primary",
                    use_container_width=True,
                )

            with btn_col2:
                if st.button("Return to Main Menu", use_container_width=True, key="return_after_audio"):
                    for key in ["_audio_file_paths", "_folder_analysis", "_filename_analysis", "_audio_link_result", "_audio_link_platform", "_audio_generate_params"]:
                        if key in st.session_state:
                            del st.session_state[key]
                    go_back_to_menu()

            st.markdown("---")

            st.markdown("**Updated Database Preview:**")
            # Show key columns: index, gloss, then all link columns, then all path columns
            preview_cols = []

            # Add index and gloss first
            if 'index' in result.df.columns:
                preview_cols.append('index')
            if 'gloss' in result.df.columns:
                preview_cols.append('gloss')

            # Add all link columns (link, link_*)
            link_cols = sorted([c for c in result.df.columns if c == 'link' or c.startswith('link_')])
            preview_cols.extend(link_cols)

            # Add all path columns (path, path_*)
            path_cols = sorted([c for c in result.df.columns if c == 'path' or c.startswith('path_')])
            preview_cols.extend(path_cols)

            # Filter to only columns that exist
            available_cols = [c for c in preview_cols if c in result.df.columns]

            if available_cols:
                st.dataframe(result.df[available_cols].head(15), use_container_width=True)
            else:
                st.dataframe(result.df.head(15), use_container_width=True)

        # Show analysis info if file uploaded but not yet processed
        elif "_folder_analysis" in st.session_state:
            folder_analysis = st.session_state._folder_analysis
            filename_analysis = st.session_state._filename_analysis
            file_paths = st.session_state._audio_file_paths

            st.info("File list uploaded. Configure mapping and click **Add Audio Links**.")

            st.markdown("---")

            st.markdown("**Analysis Results:**")
            st.markdown(f"- Total .wav files: {folder_analysis.total_files}")
            st.markdown(f"- Subfolders: {'Yes' if folder_analysis.has_subfolders else 'No'}")
            if folder_analysis.has_subfolders:
                st.markdown(f"  - Names: {', '.join(folder_analysis.subfolder_names[:5])}" +
                            (f" ... +{len(folder_analysis.subfolder_names) - 5} more" if len(folder_analysis.subfolder_names) > 5 else ""))

            st.markdown(f"- Delimiter: `{filename_analysis.delimiter}`" if filename_analysis.delimiter else "- Delimiter: None")
            st.markdown(f"- Example: `{filename_analysis.example_filename}`")
            if filename_analysis.all_integers:
                st.markdown("- Structure: Index numbers only")
            elif filename_analysis.num_sections > 1:
                st.markdown(f"- Sections: {filename_analysis.num_sections} ({' | '.join(filename_analysis.example_sections)})")

        else:
            # Initial state - show instructions
            st.info("Download the file list generator, run it on your audio folder, then upload the result.")

            st.markdown("---")

            st.markdown("**About Audio Links**")
            st.markdown(
                """
                This task links your audio recordings to database entries by matching
                filenames to index values.

                **Two output modes:**

                - **Phonological Analysis**: One audio file per index. The same path
                  appears on all rows sharing that index (useful for compound entries).

                - **Acoustic Phonetic Analysis**: One row per audio file. The database
                  expands to have a separate row for each recording (useful for
                  analyzing multiple speakers/tokens).

                **Output columns:**
                - `path`: Full file path to the audio file
                - `link`: Clickable link (Excel on Windows) or terminal command (Mac)
                """
            )

            st.markdown("---")

            st.markdown("**Example (before):**")
            example_before = pd.DataFrame({
                'index': [1, 2, 3],
                'gloss': ['dog', 'wolf', 'cat'],
                'entry': ['maː', 'paː', 'kaː']
            })
            st.dataframe(example_before, use_container_width=True, hide_index=True)

            st.markdown("**Example (after):**")
            example_after = pd.DataFrame({
                'index': [1, 2, 3],
                'gloss': ['dog', 'wolf', 'cat'],
                'entry': ['maː', 'paː', 'kaː'],
                'link': ['listen', 'listen', 'listen'],
                'path': ['C:\\audio\\1.wav', 'C:\\audio\\2.wav', 'C:\\audio\\3.wav']
            })
            st.dataframe(example_after, use_container_width=True, hide_index=True)
